### ISSUE TITLE
establish a proper database backend

### ISSUE THREAD

**Issue by mattStorer** [OHSUCMP/ecp-sds#4]
the RDS currently employs an H2 database that came bundled with the repository.  it needs to have a more robust data store backed by a proper database.  build this out.

**Comment by mattStorer** [comment]
well, it turns out that MySQL isn't supported by hapi-fhir, calling it "deprecated."

rude.

**Comment by mattStorer** [comment]
hmm... got PostgreSQL 15.1 installed, sorted out creating a user and getting application.properties configured per [instructions](https://github.com/hapifhir/hapi-fhir-jpaserver-starter#postgresql-configuration), but getting an error when starting the service:

Stack trace:
```
2023-02-07 16:55:41.511 [main] INFO  com.zaxxer.hikari.pool.HikariPool [HikariPool.java:565] HikariPool-1 - Added connection org.postgresql.jdbc.PgConnection@b7cc0daa
2023-02-07 16:55:41.518 [main] INFO  com.zaxxer.hikari.HikariDataSource [HikariDataSource.java:123] HikariPool-1 - Start completed.
2023-02-07 16:55:41.559 [main] INFO  org.hibernate.dialect.Dialect [Dialect.java:175] HHH000400: Using dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirH2Dialect
2023-02-07 16:55:41.631 [main] WARN  c.zaxxer.hikari.pool.ProxyConnection [ProxyConnection.java:177] HikariPool-1 - Connection org.postgresql.jdbc.PgConnection@b7cc0daa marked as broken because of SQLSTATE(0A000), ErrorCode(0)
java.sql.SQLFeatureNotSupportedException: Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented.
        at org.postgresql.Driver.notImplemented(Driver.java:731)
        at org.postgresql.jdbc.PgConnection.createClob(PgConnection.java:1371)
        at com.zaxxer.hikari.pool.HikariProxyConnection.createClob(HikariProxyConnection.java)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl.useContextualLobCreation(LobCreatorBuilderImpl.java:121)
        at org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl.makeLobCreatorBuilder(LobCreatorBuilderImpl.java:56)
        at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentImpl.<init>(JdbcEnvironmentImpl.java:286)
        at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:114)
        at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:35)
```

shouldn't `createClob` be implemented?  PostgreSQL is supposed to be supported ... ?

**Comment by mattStorer** [comment]
so the error above was caused by the property `hibernate.dialect` in application.yaml being set to `ca.uhn.fhir.jpa.model.dialect.HapiFhirH2Dialect` when it needed to be `ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgres94Dialect`.  changing that property got me past that error, but yielded another error whereby database tables weren't getting created due to a permissions issue ("permission denied for schema public").  *that* issue was caused by the specified database user in application.yaml not being the database owner, when it needs to be the owner - evidently, in PostgreSQL 15, only the database owner can `CREATE` stuff (see [this StackOverflow post](https://stackoverflow.com/questions/74110708/postgres-15-permission-denied-for-schema-public) on the topic).

after sorting these issues, running the service auto generates all tables and other artifacts in the database, so looks like things are good in that respect!

**Comment by mattStorer** [comment]
created a separate "application.yaml" config that contains local updates to connect to the ecp-sds PostgreSQL database (under the *local-config* folder), along with a batch file (*run_local_config.bat*) to run the service using that local config.  purpose of this is to keep the application.yaml configuration in the *resources/* folder within the JAR unmodified to facilitate normal testing routines to complete happily, while allowing us to configure the system as we like for it to be configured when we run it.

**Comment by mattStorer** [comment]
successfully posted a Patient resource to the ecp-sds server and verified its existence in the PostgreSQL database!
![image](https://user-images.githubusercontent.com/979938/217647965-2168d971-85f0-4d37-a509-ae17d4ed434e.png)
